name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 10.5.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^6.0.6
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.14
  flutter_vector_icons: ^2.0.0
  country_picker: ^2.0.21

  #Firebase
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_remote_config: ^4.2.7
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  firebase_pagination: ^3.0.0
  webview_flutter: ^3.0.4

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.2.1

  #image:
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  file_picker: ^6.0.0
  lottie: ^2.6.0

  # PAYMENTS
  flutter_stripe: ^9.4.0
  flutterwave_standard: ^1.0.8
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  #notifications:
  onesignal_flutter: ^3.5.1
  flutter_typeahead: ^4.6.2

  #chart
  syncfusion_flutter_charts: ^23.1.40

  #map:
  geocoding: ^2.1.1
  flutter_html: ^3.0.0-alpha.3
  flutter_image_stack: ^0.0.7
  android_intent_plus: ^4.0.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

